all: exerc01 exerc02 exerc03

exerc01: exerc01.c
	gcc exerc01.c -o exerc01 -lufr -I../include

exerc02: exerc02.c
	gcc exerc02.c -o exerc02 -lufr -I../include

exerc03: exerc03.c
	gcc exerc03.c -o exerc03 -lufr -I../include

clean:
	rm -f exerc01 exerc02 exerc03